# A subset of popular NSE tickers for the autocomplete demo.
# In production, you would load this from a full CSV.

NSE_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LICI.NS", "LT.NS", "AXISBANK.NS", "HCLTECH.NS", "BAJFINANCE.NS",
    "ASIANPAINT.NS", "MARUTI.NS", "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS",
    "WIPRO.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "TATAMOTORS.NS",
    "ADANIENT.NS", "JSWSTEEL.NS", "M&M.NS", "ADANIPORTS.NS", "COALINDIA.NS",
    "TATASTEEL.NS", "BAJAJFINSV.NS", "HINDALCO.NS", "GRASIM.NS", "EICHERMOT.NS",
    "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "BRITANNIA.NS", "INDUSINDBK.NS",
    "TECHM.NS", "TATACONSUM.NS", "APOLLOHOSP.NS", "BPCL.NS", "HEROMOTOCO.NS",
    "UPL.NS", "SBILIFE.NS", "HDFCLIFE.NS", "ZOMATO.NS", "PAYTM.NS", "POLICYBZR.NS",
    "HAL.NS", "BEL.NS", "TRENT.NS", "VBL.NS", "ABBOTINDIA.NS", "PIIND.NS",
    "PAGEIND.NS", "SRF.NS", "MRF.NS", "BOSCHLTD.NS", "COLPAL.NS", "HAVELLS.NS",
    "DABUR.NS", "GODREJCP.NS", "SHREECEM.NS", "PIDILITIND.NS", "SIEMENS.NS",
    "ABB.NS", "NAUKRI.NS", "DLF.NS", "LTIM.NS", "MOTHERSON.NS", "IRCTC.NS", "LALPATHLAB.NS",
    "BAJAJHFL.NS", "TATAELXSI.NS", "HDFCGOLD.NS", "NESTLEIND.NS", "GMMPFAUDLR.NS",
    "CLEAN.NS"
]